roboto_usb2can: src/led.c File Reference
led.c File Reference
#include "roboto_usb2can.h"
Functions
LOG_MODULE_REGISTER (status_led, LOG_LEVEL_INF)
static void usb_led_blink_work (struct k_work *work)
static void can_led_blink_work (struct k_work *work)
static void activity_led_off_work (struct k_work *work)
static void activity_tick_handler (struct k_timer *timer)
int status_led_init (void)
Initialize the status LED system.
void status_led_usb_set (enum led_status status)
Set USB LED status (Blue LED)
void status_led_can_set (enum can_led_status status)
Set CAN LED status (Yellow LED)
void status_led_can_activity (void)
Indicate CAN bus activity (Green LED)
int status_led_event (const struct device *dev, uint16_t ch, enum gs_usb_event event, void *user_data)
GS-USB event callback for LED status updates.
Variables
const struct gpio_dt_spec usb_led = gpio_spec
const struct gpio_dt_spec activity_led = gpio_spec
const struct gpio_dt_spec can_led = gpio_spec
struct k_work_delayable usb_led_work
struct k_work_delayable can_led_work
struct k_work_delayable activity_work
enum led_status current_usb_status = LED_USB_READY
int usb_repeat_count = 0
bool usb_led_state = false
enum can_led_status current_can_status = CAN_LED_OFF
int can_repeat_count = 0
bool can_led_state = false
struct k_timer activity_tick_timer
k_timepoint_t last_activity_time
int activity_ticks = 0
k_timepoint_t last_stopped_time
Function Documentation
activity_led_off_work()
static void activity_led_off_work (struct k_work * work) static
Definition at line 96 of file led.c.
References activity_led.
Referenced by status_led_init().
activity_tick_handler()
static void activity_tick_handler (struct k_timer * timer) static
Definition at line 102 of file led.c.
References activity_led, activity_ticks, and LED_TICKS_ACTIVITY.
Referenced by status_led_init().
can_led_blink_work()
static void can_led_blink_work (struct k_work * work) static
Definition at line 65 of file led.c.
References can_led, can_led_patterns, can_led_state, can_led_work, can_repeat_count, current_can_status, led_pattern::off_ms, led_pattern::on_ms, and led_pattern::repeat.
Referenced by status_led_init().
LOG_MODULE_REGISTER()
LOG_MODULE_REGISTER (status_led , LOG_LEVEL_INF)
status_led_can_activity()
void status_led_can_activity (void)
Indicate CAN bus activity (Green LED)
Briefly flashes the green LED to show CAN data transmission or reception activity. This function is typically called from interrupt context.
Definition at line 225 of file led.c.
References activity_led, activity_ticks, and LED_TICKS_ACTIVITY.
Referenced by status_led_event().
status_led_can_set()
void status_led_can_set (enum can_led_status status)
Set CAN LED status (Yellow LED)
Controls the yellow LED to indicate CAN system status with different blink patterns.
Parameters
status CAN status to display (CAN_LED_OFF, CAN_LED_ACTIVE, etc.)
Definition at line 202 of file led.c.
References can_led, can_led_patterns, can_led_state, can_led_work, can_repeat_count, current_can_status, and led_pattern::on_ms.
Referenced by can_state_change_callback(), status_led_event(), and status_led_init().
status_led_event()
int status_led_event (const struct device * dev, uint16_t ch, enum gs_usb_event event, void * user_data)
GS-USB event callback for LED status updates.
Callback function registered with the GS-USB stack to receive bus events and update LED status accordingly.
Parameters
dev Pointer to the device
ch Channel number
event GS-USB event type
user_data User data pointer
Returns
0 on success, negative error code on failure
Definition at line 236 of file led.c.
References CAN_LED_ACTIVE, CAN_LED_OFF, last_activity_time, last_stopped_time, LED_TICK_MS, LED_TICKS_ACTIVITY, LED_USB_READY, MIN_STOP_INTERVAL_MS, status_led_can_activity(), status_led_can_set(), and status_led_usb_set().
Referenced by main().
status_led_init()
int status_led_init (void)
Initialize the status LED system.
Sets up GPIO pins and work queues for the three-LED status indication system. Must be called before using any other LED functions.
Returns
0 on success, negative error code on failure
Definition at line 119 of file led.c.
References activity_led, activity_led_off_work(), activity_tick_handler(), activity_tick_timer, activity_work, can_led, can_led_blink_work(), CAN_LED_OFF, can_led_work, last_activity_time, last_stopped_time, LED_TICK_MS, LED_USB_READY, status_led_can_set(), status_led_usb_set(), usb_led, usb_led_blink_work(), and usb_led_work.
Referenced by main().
status_led_usb_set()
void status_led_usb_set (enum led_status status)
Set USB LED status (Blue LED)
Controls the blue LED to indicate USB system status with different blink patterns.
Parameters
status USB status to display (LED_USB_READY or LED_USB_ERROR)
Definition at line 179 of file led.c.
References current_usb_status, led_pattern::on_ms, usb_led, usb_led_patterns, usb_led_state, usb_led_work, and usb_repeat_count.
Referenced by can_state_change_callback(), main(), status_led_event(), and status_led_init().
usb_led_blink_work()
static void usb_led_blink_work (struct k_work * work) static
Definition at line 34 of file led.c.
References current_usb_status, led_pattern::off_ms, led_pattern::on_ms, led_pattern::repeat, usb_led, usb_led_patterns, usb_led_state, usb_led_work, and usb_repeat_count.
Referenced by status_led_init().
Variable Documentation
activity_led
const struct gpio_dt_spec activity_led = gpio_spec
Definition at line 11 of file led.c.
Referenced by activity_led_off_work(), activity_tick_handler(), status_led_can_activity(), and status_led_init().
activity_tick_timer
struct k_timer activity_tick_timer
Definition at line 28 of file led.c.
Referenced by status_led_init().
activity_ticks
int activity_ticks = 0
Definition at line 30 of file led.c.
Referenced by activity_tick_handler(), and status_led_can_activity().
activity_work
struct k_work_delayable activity_work
Definition at line 17 of file led.c.
Referenced by status_led_init().
can_led
const struct gpio_dt_spec can_led = gpio_spec
Definition at line 12 of file led.c.
Referenced by can_led_blink_work(), status_led_can_set(), and status_led_init().
can_led_state
bool can_led_state = false
Definition at line 25 of file led.c.
Referenced by can_led_blink_work(), and status_led_can_set().
can_led_work
struct k_work_delayable can_led_work
Definition at line 16 of file led.c.
Referenced by can_led_blink_work(), status_led_can_set(), and status_led_init().
can_repeat_count
int can_repeat_count = 0
Definition at line 24 of file led.c.
Referenced by can_led_blink_work(), and status_led_can_set().
current_can_status
enum can_led_status current_can_status = CAN_LED_OFF
Definition at line 23 of file led.c.
Referenced by can_led_blink_work(), and status_led_can_set().
current_usb_status
enum led_status current_usb_status = LED_USB_READY
Definition at line 20 of file led.c.
Referenced by status_led_usb_set(), and usb_led_blink_work().
last_activity_time
k_timepoint_t last_activity_time
Definition at line 29 of file led.c.
Referenced by status_led_event(), and status_led_init().
last_stopped_time
k_timepoint_t last_stopped_time
Definition at line 31 of file led.c.
Referenced by status_led_event(), and status_led_init().
usb_led
const struct gpio_dt_spec usb_led = gpio_spec
Definition at line 10 of file led.c.
Referenced by status_led_init(), status_led_usb_set(), and usb_led_blink_work().
usb_led_state
bool usb_led_state = false
Definition at line 22 of file led.c.
Referenced by status_led_usb_set(), and usb_led_blink_work().
usb_led_work
struct k_work_delayable usb_led_work
Definition at line 15 of file led.c.
Referenced by status_led_init(), status_led_usb_set(), and usb_led_blink_work().
usb_repeat_count
int usb_repeat_count = 0
Definition at line 21 of file led.c.
Referenced by status_led_usb_set(), and usb_led_blink_work().