roboto_usb2can: src/main.c File Reference
main.c File Reference
#include "roboto_usb2can.h"
Functions
LOG_MODULE_REGISTER (main, LOG_LEVEL_INF)
USBD_DEVICE_DEFINE (usbd, device_ptr, 0x1D50, 0x606F)
USBD_DESC_LANG_DEFINE (lang)
USBD_DESC_MANUFACTURER_DEFINE (mfr, "wentywenty")
USBD_DESC_PRODUCT_DEFINE (product, "roboto_usb2can")
USBD_DESC_SERIAL_NUMBER_DEFINE (sn)
USBD_DESC_CONFIG_DEFINE (fs_config_desc, "Full-Speed Configuration")
USBD_CONFIGURATION_DEFINE (fs_config, 0, 250, &fs_config_desc)
static int msos_vendor_handler (const struct usbd_context *const ctx, const struct usb_setup_packet *const setup, struct net_buf *const buf)
Microsoft OS 2.0 descriptor vendor request handler.
USBD_DESC_BOS_DEFINE (bos_lpm, sizeof(bos_cap_lpm), &bos_cap_lpm)
USBD_DESC_BOS_VREQ_DEFINE (bos_msosv2, sizeof(bos_cap_msosv2), &bos_cap_msosv2, 0x01, msos_vendor_handler, NULL)
static void can_state_change_callback (const struct device *dev, enum can_state state, struct can_bus_err_cnt err_cnt, void *user_data)
CAN state change callback - Error monitoring and protection.
int main (void)
Main application entry point.
Function Documentation
can_state_change_callback()
static void can_state_change_callback (const struct device * dev, enum can_state state, struct can_bus_err_cnt err_cnt, void * user_data) static
CAN state change callback - Error monitoring and protection.
This callback monitors CAN bus state changes and implements error protection mechanisms including error frame flood detection and automatic bus-off recovery.
Parameters
dev Pointer to the CAN device
state Current CAN bus state
err_cnt CAN error counters (TX/RX)
user_data User data pointer (channel index)
Definition at line 57 of file main.c.
References CAN_ERR_FRAME_THRESHOLD, CAN_ERR_PASSIVE_LIMIT, CAN_ERR_WINDOW_MS, CAN_LED_ACTIVE, CAN_LED_ERROR, CAN_LED_OFF, CAN_LED_WARNING, can_error_monitor::err_frame_count, can_error_monitor::err_passive_count, can_error_monitor::forced_busoff, LED_USB_ERROR, status_led_can_set(), status_led_usb_set(), can_error_monitor::throttled, and can_error_monitor::window_start_ms.
Referenced by main().
LOG_MODULE_REGISTER()
LOG_MODULE_REGISTER (main , LOG_LEVEL_INF)
main()
int main (void)
Main application entry point.
Initializes the roboto_usb2can adapter including:
Status LED system
CAN error monitoring
GS-USB protocol stack
USB device configuration (WinUSB support)
Returns
0 on success, negative error code on failure
Definition at line 161 of file main.c.
References can_state_change_callback(), LED_USB_READY, status_led_event(), status_led_init(), and status_led_usb_set().
msos_vendor_handler()
static int msos_vendor_handler (const struct usbd_context *const ctx, const struct usb_setup_packet *const setup, struct net_buf *const buf) static
Microsoft OS 2.0 descriptor vendor request handler.
Handles Windows-specific vendor requests for MSOS 2.0 descriptors, enabling automatic WinUSB driver binding without manual driver installation.
Parameters
ctx USB device context
setup USB setup packet containing the request
buf Network buffer for response data
Returns
0 on success, -ENOTSUP for unsupported requests
Definition at line 28 of file main.c.
References msos2_desc.
USBD_CONFIGURATION_DEFINE()
USBD_CONFIGURATION_DEFINE (fs_config , 0 , 250 , & fs_config_desc)
USBD_DESC_BOS_DEFINE()
USBD_DESC_BOS_DEFINE (bos_lpm , sizeof(bos_cap_lpm) , & bos_cap_lpm)
USBD_DESC_BOS_VREQ_DEFINE()
USBD_DESC_BOS_VREQ_DEFINE (bos_msosv2 , sizeof(bos_cap_msosv2) , & bos_cap_msosv2, 0x01 , msos_vendor_handler , NULL)
USBD_DESC_CONFIG_DEFINE()
USBD_DESC_CONFIG_DEFINE (fs_config_desc , "Full-Speed Configuration")
USBD_DESC_LANG_DEFINE()
USBD_DESC_LANG_DEFINE (lang)
USBD_DESC_MANUFACTURER_DEFINE()
USBD_DESC_MANUFACTURER_DEFINE (mfr , "wentywenty")
USBD_DESC_PRODUCT_DEFINE()
USBD_DESC_PRODUCT_DEFINE (product , "roboto_usb2can")
USBD_DESC_SERIAL_NUMBER_DEFINE()
USBD_DESC_SERIAL_NUMBER_DEFINE (sn)
USBD_DEVICE_DEFINE()
USBD_DEVICE_DEFINE (usbd , device_ptr , 0x1D50 , 0x606F)