roboto_usb2can: src/roboto_usb2can.h File Reference
roboto_usb2can.h File Reference
#include <zephyr/device.h>
#include <zephyr/devicetree.h>
#include <zephyr/drivers/can.h>
#include <zephyr/drivers/gpio.h>
#include <zephyr/kernel.h>
#include <cannectivity/usb/class/gs_usb.h>
#include <zephyr/logging/log.h>
#include "version.h"
#include <zephyr/usb/usbd.h>
#include <zephyr/usb/msos_desc.h>
#include <zephyr/sys/byteorder.h>
Classes
struct msos2_descriptor
struct usb_bos_msosv2
struct can_error_monitor
struct led_pattern
Macros
#define COMPATIBLE_ID_WINUSB 'W', 'I', 'N', 'U', 'S', 'B', 0x00, 0x00
#define GS_USB_DEVICE_INTERFACE_GUID
#define CAN_ERR_FRAME_THRESHOLD 50 /* Max 50 error frames allowed per second */
#define CAN_ERR_WINDOW_MS 1000 /* Statistics window 1 second */
#define CAN_ERR_PASSIVE_LIMIT 10 /* Force Bus-Off after 10 accumulated ERROR_PASSIVE */
#define MIN_STOP_INTERVAL_MS 1000 /* STOP events within 1 second are considered abnormal */
#define LED_TICK_MS 50 /* Timer triggers every 50ms */
#define LED_TICKS_ACTIVITY 2 /* Activity LED on for 2 ticks (100ms) */
Enumerations
enum led_status { LED_USB_READY , LED_USB_ERROR }
enum can_led_status { CAN_LED_OFF , CAN_LED_ACTIVE , CAN_LED_WARNING , CAN_LED_ERROR }
Functions
struct msos2_descriptor __attribute__ ((packed))
static struct can_error_monitor err_monitors[1] __attribute__ ((unused))
int status_led_init (void)
Initialize the status LED system.
void status_led_usb_set (enum led_status status)
Set USB LED status (Blue LED)
void status_led_can_set (enum can_led_status status)
Set CAN LED status (Yellow LED)
void status_led_can_activity (void)
Indicate CAN bus activity (Green LED)
int status_led_event (const struct device *dev, uint16_t ch, enum gs_usb_event event, void *user_data)
GS-USB event callback for LED status updates.
Variables
struct msosv2_descriptor_set_header header
struct msosv2_compatible_id compatible_id
struct msosv2_guids_property guids_property
static const struct msos2_descriptor msos2_desc
static const struct usb_bos_capability_lpm bos_cap_lpm
struct usb_bos_platform_descriptor platform
struct usb_bos_capability_msos cap
static const struct usb_bos_msosv2 bos_cap_msosv2
struct can_error_monitor __attribute__
static const struct led_pattern usb_led_patterns []
static const struct led_pattern can_led_patterns []
Macro Definition Documentation
CAN_ERR_FRAME_THRESHOLD
#define CAN_ERR_FRAME_THRESHOLD 50 /* Max 50 error frames allowed per second */
Definition at line 116 of file roboto_usb2can.h.
CAN_ERR_PASSIVE_LIMIT
#define CAN_ERR_PASSIVE_LIMIT 10 /* Force Bus-Off after 10 accumulated ERROR_PASSIVE */
Definition at line 118 of file roboto_usb2can.h.
CAN_ERR_WINDOW_MS
#define CAN_ERR_WINDOW_MS 1000 /* Statistics window 1 second */
Definition at line 117 of file roboto_usb2can.h.
COMPATIBLE_ID_WINUSB
#define COMPATIBLE_ID_WINUSB 'W', 'I', 'N', 'U', 'S', 'B', 0x00, 0x00
Definition at line 22 of file roboto_usb2can.h.
GS_USB_DEVICE_INTERFACE_GUID
#define GS_USB_DEVICE_INTERFACE_GUID
Value:
    '{', 0x00, 'c', 0x00, '6', 0x00, 'e', 0x00, '5', 0x00, '1', 0x00, '5', 0x00, 'a', 0x00,    \
        '2', 0x00, '-', 0x00, '8', 0x00, 'd', 0x00, 'c', 0x00, '6', 0x00, '-', 0x00, '4',  \
        0x00, 'f', 0x00, 'c', 0x00, '4', 0x00, '-', 0x00, 'a', 0x00, '0', 0x00, '3', 0x00, \
        'c', 0x00, '-', 0x00, '9', 0x00, '3', 0x00, '2', 0x00, '5', 0x00, '5', 0x00, '5',  \
        0x00, 'd', 0x00, '6', 0x00, '8', 0x00, 'e', 0x00, '6', 0x00, '}', 0x00, 0x00, 0x00
Definition at line 24 of file roboto_usb2can.h.
LED_TICK_MS
#define LED_TICK_MS 50 /* Timer triggers every 50ms */
Definition at line 151 of file roboto_usb2can.h.
LED_TICKS_ACTIVITY
#define LED_TICKS_ACTIVITY 2 /* Activity LED on for 2 ticks (100ms) */
Definition at line 152 of file roboto_usb2can.h.
MIN_STOP_INTERVAL_MS
#define MIN_STOP_INTERVAL_MS 1000 /* STOP events within 1 second are considered abnormal */
Definition at line 150 of file roboto_usb2can.h.
Enumeration Type Documentation
can_led_status
enum can_led_status
Enumerator
CAN_LED_OFF
CAN_LED_ACTIVE
CAN_LED_WARNING
CAN_LED_ERROR
Definition at line 142 of file roboto_usb2can.h.
led_status
enum led_status
Enumerator
LED_USB_READY
LED_USB_ERROR
Definition at line 135 of file roboto_usb2can.h.
Function Documentation
__attribute__() [1/2]
struct msos2_descriptor __attribute__ ((packed))
__attribute__() [2/2]
static struct can_error_monitor err_monitors[1] __attribute__ ((unused)) static
status_led_can_activity()
void status_led_can_activity (void)
Indicate CAN bus activity (Green LED)
Briefly flashes the green LED to show CAN data transmission or reception activity. This function is typically called from interrupt context.
Definition at line 225 of file led.c.
References activity_led, activity_ticks, and LED_TICKS_ACTIVITY.
Referenced by status_led_event().
status_led_can_set()
void status_led_can_set (enum can_led_status status)
Set CAN LED status (Yellow LED)
Controls the yellow LED to indicate CAN system status with different blink patterns.
Parameters
status CAN status to display (CAN_LED_OFF, CAN_LED_ACTIVE, etc.)
Definition at line 202 of file led.c.
References can_led, can_led_patterns, can_led_state, can_led_work, can_repeat_count, current_can_status, and led_pattern::on_ms.
Referenced by can_state_change_callback(), status_led_event(), and status_led_init().
status_led_event()
int status_led_event (const struct device * dev, uint16_t ch, enum gs_usb_event event, void * user_data)
GS-USB event callback for LED status updates.
Callback function registered with the GS-USB stack to receive bus events and update LED status accordingly.
Parameters
dev Pointer to the device
ch Channel number
event GS-USB event type
user_data User data pointer
Returns
0 on success, negative error code on failure
Definition at line 236 of file led.c.
References CAN_LED_ACTIVE, CAN_LED_OFF, last_activity_time, last_stopped_time, LED_TICK_MS, LED_TICKS_ACTIVITY, LED_USB_READY, MIN_STOP_INTERVAL_MS, status_led_can_activity(), status_led_can_set(), and status_led_usb_set().
Referenced by main().
status_led_init()
int status_led_init (void)
Initialize the status LED system.
Sets up GPIO pins and work queues for the three-LED status indication system. Must be called before using any other LED functions.
Returns
0 on success, negative error code on failure
Definition at line 119 of file led.c.
References activity_led, activity_led_off_work(), activity_tick_handler(), activity_tick_timer, activity_work, can_led, can_led_blink_work(), CAN_LED_OFF, can_led_work, last_activity_time, last_stopped_time, LED_TICK_MS, LED_USB_READY, status_led_can_set(), status_led_usb_set(), usb_led, usb_led_blink_work(), and usb_led_work.
Referenced by main().
status_led_usb_set()
void status_led_usb_set (enum led_status status)
Set USB LED status (Blue LED)
Controls the blue LED to indicate USB system status with different blink patterns.
Parameters
status USB status to display (LED_USB_READY or LED_USB_ERROR)
Definition at line 179 of file led.c.
References current_usb_status, led_pattern::on_ms, usb_led, usb_led_patterns, usb_led_state, usb_led_work, and usb_repeat_count.
Referenced by can_state_change_callback(), main(), status_led_event(), and status_led_init().
Variable Documentation
__attribute__
struct usb_bos_msosv2 __attribute__
bos_cap_lpm
const struct usb_bos_capability_lpm bos_cap_lpm static
Initial value:
= {
    .bLength = sizeof(struct usb_bos_capability_lpm),
    .bDescriptorType = USB_DESC_DEVICE_CAPABILITY,
    .bDevCapabilityType = USB_BOS_CAPABILITY_EXTENSION,
    .bmAttributes = 0UL,
}
Definition at line 65 of file roboto_usb2can.h.
bos_cap_msosv2
const struct usb_bos_msosv2 bos_cap_msosv2 static
Definition at line 78 of file roboto_usb2can.h.
can_led_patterns
const struct led_pattern can_led_patterns[] static
Initial value:
= {
    [CAN_LED_OFF] = {50, 3950, -1},
    [CAN_LED_ACTIVE] = {500, 500, -1},
    [CAN_LED_WARNING] = {200, 1800, -1},
    [CAN_LED_ERROR] = {100, 100, -1},
}
Definition at line 168 of file roboto_usb2can.h.
Referenced by can_led_blink_work(), and status_led_can_set().
cap
struct usb_bos_capability_msos cap
Definition at line 1 of file roboto_usb2can.h.
compatible_id
struct msosv2_compatible_id compatible_id
Definition at line 1 of file roboto_usb2can.h.
guids_property
struct msosv2_guids_property guids_property
Definition at line 2 of file roboto_usb2can.h.
header
struct msosv2_descriptor_set_header header
Definition at line 0 of file roboto_usb2can.h.
msos2_desc
const struct msos2_descriptor msos2_desc static
Initial value:
= {
    .header =
        {
            .wLength = sizeof(struct msosv2_descriptor_set_header),
            .wDescriptorType = MS_OS_20_SET_HEADER_DESCRIPTOR,
            .dwWindowsVersion = 0x06030000,
            .wTotalLength = sizeof(struct msos2_descriptor),
        },
    .compatible_id =
        {
            .wLength = sizeof(struct msosv2_compatible_id),
            .wDescriptorType = MS_OS_20_FEATURE_COMPATIBLE_ID,
            .CompatibleID = {COMPATIBLE_ID_WINUSB},
        },
    .guids_property =
        {
            .wLength = sizeof(struct msosv2_guids_property),
            .wDescriptorType = MS_OS_20_FEATURE_REG_PROPERTY,
            .wPropertyDataType = MS_OS_20_PROPERTY_DATA_REG_MULTI_SZ,
            .wPropertyNameLength = 42,
            .PropertyName = {DEVICE_INTERFACE_GUIDS_PROPERTY_NAME},
            .wPropertyDataLength = 80,
            .bPropertyData = {GS_USB_DEVICE_INTERFACE_GUID},
        },
}
Definition at line 38 of file roboto_usb2can.h.
Referenced by msos_vendor_handler().
platform
struct usb_bos_platform_descriptor platform
Definition at line 0 of file roboto_usb2can.h.
usb_led_patterns
const struct led_pattern usb_led_patterns[] static
Initial value:
= {
    [LED_USB_READY] = {500, 500, -1},
    [LED_USB_ERROR] = {100, 100, -1},
}
Definition at line 162 of file roboto_usb2can.h.
Referenced by status_led_usb_set(), and usb_led_blink_work().